QA output created by 645
Log for pmlogger on HOST started DATE

[DATE] pmlogger(PID) Error: gethostbyname(nosuchhost.pcp.io), Unknown host
error was on line 4

Log finished DATE
Log for pmlogger on HOST started DATE

[DATE] pmlogger(PID) Error: gethostbyname(no-such-host.pcp.io), Unknown host
error was on line 4

Log finished DATE
